version: '3'
services:
  # the hello world service
  # deployment-ready.
  hello-service:
    build: ./internal-microservices/hello-service/.
    restart: on-failure
    ports: 
      - 1000:3000
    env_file:
      - ./internal-microservices/hello-service/src/.env
  
  # database service
  mongodb:
    image: mongo
    restart: on-failure
    ports: 
      - 27017:27017
    volumes:
      - ./data/mongod/:/data/db
    env_file:
      - ./databases/mongo/.env

  # the authentication microservice
  authentication:
    build: ./internal-microservices/authentication-service/.
    restart: on-failure
    ports: 
      - 1001:3000
    env_file:
      - ./internal-microservices/authentication-service/src/.env
    depends_on:
      - mongodb # want mongodb to start up before this.
  

  # mysql database
  mysqldb:
    image: mysql:5.7
    restart: on-failure
    env_file:
      - ./databases/mysql/.env
    volumes:
      - ./data/mysqld:/var/lib/mysql
    ports:
      - 3306:3306

  # blog microservice
  ghost:
    image: ghost:4-alpine
    restart: on-failure
    ports: 
      - 2000:2368
    env_file:
      - ./external-microservices/ghost/.env
    volumes:
      - ./data/ghost/:/var/lib/ghost/content
    depends_on:
      - mysqldb
  
  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 4000:8080

  # database viewer service
  mongo-express:
    image: mongo-express
    restart: on-failure
    ports: 
      - 4001:8081
    depends_on:
      - mongodb
    env_file:
      - ./external-microservices/mongo-express/.env
  
  # nginx:
  #   image: nginx:1.17.10
  #   restart: on-failure
  #   volumes:
  #     - ./loadbalancer/nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - 80:80
  #     - 443:443
  #   depends_on:
  #     - hello-service
  #     - mongo-express
  #     - adminer
  #     - mysqldb
  #     - mongodb
  #     - ghost
  #     - authentication

  nginx:
    build: ./loadbalancer/.
    restart: on-failure
    # volumes:
    #   - ./loadbalancer/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - hello-service
      - mongo-express
      - adminer
      - mysqldb
      - mongodb
      - ghost
      - authentication